### ISSUE TITLE
OSError: ``/content/gdrive/MyDrive/ecg-mit-bih/src/dataset/train.hdf5`` does not exist

### ISSUE THREAD

**Issue by sg4395** [physhik/ecg-mit-bih#18]
Hi this is the error, are you able to help me work through this?  Please let me know thank you!

feature: MLII
Traceback (most recent call last):
  File "train.py", line 59, in <module>
    main(config)
  File "train.py", line 54, in main
    (X,y, Xval, yval) = loaddata(config.input_size, config.feature)
  File "/content/gdrive/MyDrive/ecg-mit-bih/src/utils.py", line 21, in loaddata
    trainData = ddio.load('dataset/train.hdf5')
  File "/usr/local/lib/python3.8/dist-packages/deepdish/io/hdf5io.py", line 636, in load
    with tables.open_file(path, mode='r') as h5file:
  File "/usr/local/lib/python3.8/dist-packages/tables/file.py", line 300, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tables/file.py", line 750, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 368, in tables.hdf5extension.File._g_new
  File "/usr/local/lib/python3.8/dist-packages/tables/utils.py", line 143, in check_file_access
    raise OSError(f"``{path}`` does not exist")
OSError: ``/content/gdrive/MyDrive/ecg-mit-bih/src/dataset/train.hdf5`` does not exist

**Comment by wkzqn** [comment]
谢谢。您的邮件已收到，我会尽快处理。

**Comment by sg4395** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'training2017/REFERENCE.csv'

**Comment by physhik** [comment]
> Hi this is the error, are you able to help me work through this? Please let me know thank you!
> 
> feature: MLII Traceback (most recent call last): File "train.py", line 59, in main(config) File "train.py", line 54, in main (X,y, Xval, yval) = loaddata(config.input_size, config.feature) File "/content/gdrive/MyDrive/ecg-mit-bih/src/utils.py", line 21, in loaddata trainData = ddio.load('dataset/train.hdf5') File "/usr/local/lib/python3.8/dist-packages/deepdish/io/hdf5io.py", line 636, in load with tables.open_file(path, mode='r') as h5file: File "/usr/local/lib/python3.8/dist-packages/tables/file.py", line 300, in open_file return File(filename, mode, title, root_uep, filters, **kwargs) File "/usr/local/lib/python3.8/dist-packages/tables/file.py", line 750, in **init** self._g_new(filename, mode, **params) File "tables/hdf5extension.pyx", line 368, in tables.hdf5extension.File._g_new File "/usr/local/lib/python3.8/dist-packages/tables/utils.py", line 143, in check_file_access raise OSError(f"`{path}` does not exist") OSError: `/content/gdrive/MyDrive/ecg-mit-bih/src/dataset/train.hdf5` does not exist


Did you try the following steps?
This project use old python libraries so you should install from the requirements.txt in your virtual environment
And download the data using the data.py 

$ git clone https://github.com/physhik/ecg-mit-bih.git
$ cd ecg-mit-bih
$ pip install virtualenv
$ virtualenv -p python ecg-env
$ source ./ecg-env/bin/activate
(ecg-env) $ pip install -r requrirements.txt
(ecg-env) $ python src/data.py --downloading True
(eng-env) $ python src/train.py

**Comment by physhik** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'training2017/REFERENCE.csv'

curl -O https://archive.physionet.org/challenge/2017/training2017.zip

this is explained in the predict.py file
